proxy:
  #
  #  SmartManager for ShinyProxy
  #  © 2021, YakData, LLC All Rights Reserved.
  #
  #  Distributed under the YUMMY License v1.0 - a sustainable,
  #     open-source license the license text is available at
  #     https://github.com/SmartManagerPro/ShinyProxy
  #
  # Do not change the next 2 lines until a valid license is obtained
  title: YakData SmartManager for ShinyProxy
  logo-url: /webassets/images/YakData_Logo_20171101_S_36_36.png.webp
  # Recommended to not change the following lines - breaking changes
  port: 8080
  template-path: /yakdata/config/shinyproxy/resources/templates
  server:
    forward-headers-strategy: native
  docker:
    internal-networking: true
  usage-stats-url: micrometer
  # Begin user editable section
  #    See https://www.shinyproxy.io/documentation/ for details
  authentication: simple
  admin-groups: admins
  users:
    - name: stephen
      password: ChangeMeThisReallyLonGPa$$w0rdISpractical
      groups: admins, scientists
    - name: eileen
      password: ChangeMe2BearsLovEShortPa$$w0rdwithHunnY
      groups: scientists
  # published content
  specs:
    - id: rstudio_shiny_app
      display-name: Default shiny app from RStudio
      description: Built in RStudio from YakData SmartManager, a default shiny app (not part of the shinyproxy samples.)
      container-cmd: ["R", "-e", "shiny::runApp('/yakdata/shinyproxy_content/test')"]
      container-image: yakdata/smartr
      container-network: yakdata
      container-volumes: [ "/yakdata/shinyproxy_content/test:/yakdata/shinyproxy_content/test" ]
      access-groups: [admins, scientists]
    - id: 01_hello
      display-name: Hello Application (Admins only)
      description: A sample app from the shinyproxy package demonstrating the basics of a Shiny app
      container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
      container-image: yakdata/smartr
      container-network: yakdata
      access-groups: admins
    - id: 06_tabsets
      display-name: Tabs in a shiny app
      description: A sample app from the shinyproxy package going beyond the basic layout with tabs
      container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
      container-image: yakdata/smartr
      container-network: yakdata
      access-groups: [admins, scientists]

# Recommended to not change the following lines - breaking changes
management:
  metrics:
    export:
      prometheus:
        enabled: true
