{
 "title": "Docker containers",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": { "query": "label_values(container_group)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 7, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory used / Limit",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 7 },
   "targets": [
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes{name=~\".+\"} - container_memory_usage_bytes{name=~\".+\"})  * 100 / container_spec_memory_limit_bytes{name=~\".+\"}) ) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Limit memory",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{name=~\".+\"}) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}